/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddCity` | `/AddCity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddCountry` | `/AddCountry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Countries` | `/Countries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CitiesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/City`; params?: Router.UnknownInputParams; } | { pathname: `/components/Country`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AddCity`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/CitiesStack`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddCity` | `/AddCity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddCountry` | `/AddCountry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Countries` | `/Countries`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CitiesList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/City`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Country`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AddCity`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/CitiesStack`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddCity${`?${string}` | `#${string}` | ''}` | `/AddCity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddCountry${`?${string}` | `#${string}` | ''}` | `/AddCountry${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Countries${`?${string}` | `#${string}` | ''}` | `/Countries${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/CitiesList${`?${string}` | `#${string}` | ''}` | `/components/City${`?${string}` | `#${string}` | ''}` | `/components/Country${`?${string}` | `#${string}` | ''}` | `/navigation/AddCity${`?${string}` | `#${string}` | ''}` | `/navigation/CitiesStack${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddCity` | `/AddCity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddCountry` | `/AddCountry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Countries` | `/Countries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CitiesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/City`; params?: Router.UnknownInputParams; } | { pathname: `/components/Country`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AddCity`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/CitiesStack`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
